name             'sanoid'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures sanoid'
long_description 'Installs/Configures sanoid'
version          '0.1.0'
