name             'sanoid'
maintainer       'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license          'GPL v3'
description      'Installs/Configures sanoid'
long_description 'Installs/Configures sanoid'
version          '0.1.0'